# Generated by Django 3.0.6 on 2020-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miraizura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo1'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo2'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo3'),
        ),
    ]
